datas=read.table("household_power_consumption.txt",header=TRUE,sep=";",colClasses="character")
datas[,1]=as.Date(datas$Date,"%d/%m/%Y")
datas[,2]=as.Date(datas$Time,"%H/%M/%S")
reqdata=subset(datas,datas$Date %in% as.Date(c("2007-02-01","2007-02-02")))
reqdata[,3]=as.numeric(reqdata[,3])
reqdata[,4]=as.numeric(reqdata[,4])
reqdata[,5]=as.numeric(reqdata[,5])
reqdata[,6]=as.numeric(reqdata[,6])
reqdata[,7]=as.numeric(reqdata[,7])
reqdata[,8]=as.numeric(reqdata[,8])
reqdata[,9]=as.numeric(reqdata[,9])
par(mfrow=c(1,1))
hist(reqdata[,3],col="Red",main="Global Active Power",xlab="Global Active Power (kilowatts)")
dev.copy(png,file="plot1.png")
dev.off()